# Generated by Django 5.0.3 on 2024-04-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='posterbg',
            field=models.ImageField(default=12, upload_to='posters_bg/'),
            preserve_default=False,
        ),
    ]
